### ISSUE TITLE
Add support for helper functions

### ISSUE THREAD

**Issue by imbriaco** [operable/fumanchu#6]
We should be able to define a set of helper functions that can be called from FuManchu templates to assist with rendering the output. The mapping of functions should be passed in at render time and made available within the template.

A simple example is a `join` helper that would allow you to turn a list into a string using specified delimiters. An example, using completely arbitrary syntax that I just made up and have no attachment to:

```
{{:join "," my_variable}}
```

**Comment by christophermaier** [comment]
We've moved on to using [Greenbar](https://github.com/operable/greenbar) for Cog's templating engine.
